# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"say_hello": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://LBegolu.github.io/nbdevtest/"

git_url = "https://github.com/LBegolu/nbdevtest/tree/{branch}/"

def custom_doc_links(name): return None
